### ISSUE TITLE
Simulator Repository Missing

### ISSUE THREAD

**Issue by tymanab** [iamlab-cmu/mrest-multi-resolution-transformer#1]
Hi,
It seems that your fork of the rlbench repository does not exist at the moment. As I am interested in reproducing this project, could you please make the repositories available again? Alternatively, it would be very helpful if you could provide instructions on how to integrate the original rlbench with this project.

The repositories that I am unable to clone from GitHub are as follows:

    * mrest-rlbench
    * mrest-pybullet
    * metaworld (your fork, as described in the README)

Thank you for your assistance.

**Comment by mohitsharma0690** [comment]
Hi,

Thank you for letting us know. The repos visibility was unknownlingly marked as private hence it wasn't available. I have changed it to public. You should be able to access them now.

For RLBench please use https://github.com/iamlab-cmu/mrest-rlbench 
For Metaworld please use https://github.com/iamlab-cmu/mrest-metaworld
For Ballbot (PyBullet) please use https://github.com/iamlab-cmu/mrest-pybullet/

Hopefully this resolves your issue.

**Comment by tymanab** [comment]
Thanks a lot. 
It seems that the pybullet one still not work, and the other two repository works well for me.

**Comment by mohitsharma0690** [comment]
What is the issue that  you are facing? The pybullet link above was slightly incorrect, I just updated it. If you are facing issues with installing the library can you post the stack-trace or some more information to help us debug.

**Comment by tymanab** [comment]
There is no further problem since the pybullet link fixed. 
Thanks for your help.
